language: node_js
dist: xenial
cache: yarn

jobs:
  include:
#    - stage: Static Tests
#      name: eslint
#      node_js:
#        - 10
#      script:
#        - yarn run eslint
#    - name: ShellCheck
#      script:
#        - shellcheck bin/heroku bin/setup
#      language: generic
#    - name: json-lint
#      addons:
#        apt:
#          packages:
#          - jq
#      script:
#        - yarn run jsonlint
#      language: generic
#    - stage: Dynamic Tests
#      name: Node.js 8
#      node_js:
#        - 8
#      script:
#        - yarn run mocha-suite
#    - name: Node.js 10
#      node_js:
#        - 10
#      script:
#        - yarn run mocha-suite
#    - name: Node.js 12
#      node_js:
#        - 12
#      script:
#        - yarn run mocha-suite
    - stage: Build
      name: Build front-end bundle
      node_js:
        - 12
      script:
        - yarn install --frozen-lockfile
        - yarn install --production=false --frozen-lockfile
        - yarn run build
        - zip -rq release.zip ./
#        - echo "ich bin ein Test" > release.zip

deploy:
  provider: releases
  api_key: "$GITHUB_API_TOKEN"
  file: "release.zip"
  skip_cleanup: true
  draft: true
  on:
    all_branches: true
  name: "$TRAVIS_COMMIT - Toller Release"
  body: "Ich bin ein ganz toller Release, bitte lad mich runter.\n$TRAVIS_COMMIT_MESSAGE"
