name: Build
on: [push, pull_request]

jobs:
  dynamic:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Check out code
      uses: actions/checkout@v1

    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-wersion: 12

    - run: yarn install --frozen-lockfile
    - run: yarn install --production=false --frozen-lockfile
    - run: yarn run build

    - run: zip -rq release.zip ./

    - uses: actions/upload-artifact@master
      with:
        name: release
        path: release.zip

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: release.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

